### ISSUE TITLE
The role fails with missing attribute id of ovirt_disk

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-ansible-image-template#39]
This happens specifically during the task `[oVirt.image-template : Wait until the qcow image is unlocked by the oVirt engine]`. This is the error:
```
2019-04-23 12:12:03,449 p=12149 u=jan |  TASK [oVirt.image-template : Wait until the qcow image is unlocked by the oVirt engine] ***************************************************************************************************************************
2019-04-23 12:12:03,449 p=12149 u=jan |  task path: /home/jan/repo/art_stuff/ansible-roles-deps/oVirt.image-template/tasks/qcow2_image.yml:97
2019-04-23 12:12:03,461 p=12149 u=jan |  fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'id'\n\nThe error appears to have been in '/home/jan/repo/art_stuff/ansible-roles-deps/oVirt.image-template/tasks/qcow2_image.yml': line 97, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Wait until the qcow image is unlocked by the oVirt engine\n      ^ here\n"
}
```
Here is the full log: http://pastebin.test.redhat.com/757486
I suspect the issue was introduced by commit c29e2a2e2c4e97236d965d35503bd74d404d66a3, since the roles used to work for me okay before then.

Ansible version: 2.7.5
